replicaCount: 1
image:
  repository: ghcr.io/benjamindurojaiye/devsecops-assessment/payment-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8082
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 30
  periodSeconds: 10
