apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
  selector:
    app: {{ include "transaction-service.name" . }}
