replicaCount: 2

image:
  repository: ghcr.io/YOUR_GITHUB_USER/devsecops-assessment/account-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /actuator/health
  port: 8080
readinessProbe:
  path: /actuator/health
  port: 8080

