name: ci

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build_scan_push:
    strategy:
      matrix:
        service: [account-service, transaction-service, payment-service]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run unit tests
        run: mvn -B -f sample-services/${{ matrix.service }}/pom.xml test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          REPO=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$REPO/${{ matrix.service }}:${{ github.sha }}
          echo "Building $IMAGE"
          docker build -t $IMAGE sample-services/${{ matrix.service }}
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: sarif
          output: trivy.sarif

  migrate_db:
    needs: build_scan_push
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: core
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flyway migrations
        run: |
          docker run --rm \
          -v $GITHUB_WORKSPACE/implementation/ci-cd/migrations:/flyway/sql \
          flyway/flyway \
          -url=jdbc:postgresql://host.docker.internal:5432/core \
          -user=postgres \
          -password=postgres \
          migrate

      - name: Generate SBOM for account-service
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace anchore/syft:latest ghcr.io/${{ github.repository }}/account-service:${{ github.sha }} -o json > sbom-account.json

      - name: Generate SBOM for transaction-service
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace anchore/syft:latest ghcr.io/${{ github.repository }}/transaction-service:${{ github.sha }} -o json > sbom-transaction.json

      - name: Generate SBOM for payment-service
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace anchore/syft:latest ghcr.io/${{ github.repository }}/payment-service:${{ github.sha }} -o json > sbom-payment.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sbom-account.json
            sbom-transaction.json
            sbom-payment.json

