name: ci

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build_scan_push:
    strategy:
      matrix:
        service: [account-service, transaction-service, payment-service]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run unit tests
        run: mvn -B -f sample-services/${{ matrix.service }}/pom.xml test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
          echo "Building $IMAGE"
          docker build -t $IMAGE sample-services/${{ matrix.service }}
          docker push $IMAGE

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
          format: sarif
          output: trivy.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

